version: "3.2"

services:
  db:
    image: postgres
    container_name: timeoff-db
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - timeoffnet
    volumes:
      - timeoffpgdata:/var/lib/postgresql/data
  redis:
    image: redis
    networks:
      - timeoffnet
  app:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: timeoff
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    networks:
      - timeoffnet
    env_file:
      - .env
networks:
  timeoffnet:
    driver: bridge
volumes:
  timeoffpgdata:
    driver: local
